#!/bin/zsh

#  BRANDY2.0
#
#
#  Created by Francesco Ferrari on 20/12/24.
#
cd $HOME/Brandy2.0
case $1 in
( status ) . ./netstatus.zsh ;;
( sync ) . ./projectsync.zsh ;;
( launch ) . ./launcher.zsh $2 ;;
( terminate ) . ./terminate.zsh ;;
( reboot ) . ./reboot.zsh ;;
( syncode ) . ./codesync.zsh ;;
( * ) echo "Not allowed. Usage: brandy <command>" ;;
esac
