#!/bin/zsh

#  BRANDY2.0
#
#
#  Created by Francesco Ferrari on 20/12/24.
#
cd $HOME/Brandy2.0
case $1 in
( status ) . ./netstatus.zsh ;;
( sync ) . ./projectsync.zsh ;;
( launch ) . ./launcher.zsh $2 ;;
( terminate ) . ./terminate.zsh ;;
( quit ) . ./quit.zsh ;;
( reboot ) . ./reboot.zsh ;;
( syncode ) . ./codesync.zsh ;;
( dante ) dante-cli control from-file danteconfig/$2 ;;
( dvsfixQ ) . ./routines/dvsfixQ.zsh ;;
( dvsfixA ) . ./routines/dvsfixA.zsh ;;
( "quit -r" ) . ./quitreboot.zsh ;;
( * ) echo "Not allowed. Usage: brandy <comman d>" ;;
esac
